DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS supplier_order;
CREATE TABLE supplier (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_name TEXT NOT NULL,
    phone TEXT,
    city TEXT
);
CREATE TABLE item(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    unit TEXT,
    unit_cost NUMERIC,
    supplier INTEGER REFERENCES supplier(id) NOT NULL
);
CREATE TABLE supplier_order(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE DEFAULT now(),
    item INTEGER REFERENCES item(id) NOT NULL,
    amount NUMERIC,
    total_cost NUMERIC,
    shipping_status TEXT
);